name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: webapp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build
     
      - name: Build Docker image
        run: docker build -t ecommerce-web .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p ~/ecommerce-app/frontend
            cd ~/ecommerce-app/frontend

            git pull || git clone https://github.com/Timipah-Ozori/Ecommerce-platform-GHA.git .

            docker stop ecommerce-frontend || true
            docker rm ecommerce-frontend || true

            docker build -t ecommerce-frontend .
            docker run -d -p 80:80 --name ecommerce-frontend ecommerce-frontend



